### ISSUE TITLE
P2P file transfer

### ISSUE THREAD

**Issue by Tulakshana** [Uepaa-AG/p2pkit-quickstart-android#12]
Is P2P file transfer possible?

**Comment by uepaa** [comment]
No - P2Pkit is handling the device discovery job. In a nutshell it provides the information if a i) peer is discovered ii) range of peer discovered and iii) if peer is lost. Any file share protocol can be applied on top of this information - to be handled in your app layer. Here you can choose any available SDK or build your own based on your requirements.

**Comment by Tulakshana** [comment]
Thank you.
