### ISSUE TITLE
Send messages directly between the connected devices (offline)

### ISSUE THREAD

**Issue by alexander-fischer** [Uepaa-AG/p2pkit-quickstart-android#3]
Is it possible to send messages between the devices without an internet connection? The method `sendMessage()` is just for online messages. Or will it be possible in later releases?

**Comment by thupa** [comment]
Hi!
You are right, the method `sendMessage()` is part of our online API. However, and thats the good news, in a few days we will be upgrading p2pkit to enable exchanging payload as part of the p2p discovery API, this will work using p2p and will not require internet connection..

**Comment by alexander-fischer** [comment]
This sounds great! I'm curious about it :)
