### ISSUE TITLE
Bad UX when first installing P2P Services

### ISSUE THREAD

**Issue by Dagwaging** [Uepaa-AG/p2pkit-quickstart-android#5]
Scenario:

When opening an app that requires P2P Services, the app must check whether the P2P Services app is installed and direct the user to the Play Store to install it if this is not the case.
Upon returning to the first app, the user is again presented with a notification that P2P Services is not installed, even though they just did that.

Workaround:

Open the App Overview and swipe the app away to kill it completely, then re-open it.

Cause:

KitClient seems to check whether the P2P Services package is installed when it is first instantiated, i.e. when KitClient.getInstance() is called for the first time.
If this check fails, KitClient.connect() will fail until the application is completely unloaded and reloaded, even if P2P Services has been installed in the meantime.

Solution:

Move the check for the existence of the P2P Services package out of the KitClient() constructor and into KitClient.connect().

**Comment by thupa** [comment]
Hi Dagwaging,
Thanks a lot for the detailed information!

We are trying to reproduce the issue on our end with no success, could you let us know which phones and os versions you were using?

Any info will help us track down the issue...

Thanks!

**Comment by Dagwaging** [comment]
I'm running a Nexus 6 on Marshmallow, build MRA58K. I can provide a simple project reproducing the issue if you like.

**Comment by thupa** [comment]
That would be great, please email us or provide a link to the project. We will look at it asap..

**Comment by Dagwaging** [comment]
See https://github.com/Dagwaging/Issue5
This is specifically due to keeping a static reference to KitClient around.
Avoiding this prevents the issue.

**Comment by thupa** [comment]
Hi Dagwagig,
Thanks for the information and the example code.. You are right and the current behaviour is not ideal, I therefore queued a task to fix this asap so stay tuned! 

In the meantime however, I can suggest to circumvent the issue using the same approach as in our get started app. Simply query if P2PServices is available before creating the KitClient instance (KitClient.isP2PServicesAvailable(this)). 

I hope this is ok for you, and thanks again for bringing it up and making p2pkit a better product!

Cheers

```java
@Override
protected void onStart() {
  super.onStart();
  setContentView(R.layout.activity_main);

  status = (TextView) findViewById(R.id.p2p_kit_status);

  if (KitClient.isP2PServicesAvailable(this) == ConnectionResult.SUCCESS) {
    if (client == null) {
      client = KitClient.getInstance(this);
    }

    client.registerConnectionCallbacks(this);
    client.connect(getString(R.string.p2p_kit_api_key));
  } else {
    ConnectionResultHandling.showAlertDialogForConnectionError(this,  KitClient.isP2PServicesAvailable(this));
  }
}

@Override
protected void onStop() {
  super.onStop();

  if (client != null) {
    client.unregisterConnectionCallbacks(this);
    client.disconnect();
  }
}
```

**Comment by Dagwaging** [comment]
Yes, it's not nearly as big a deal as I originally thought, given that it only occurs when keeping a static reference to KitClient (which isn't the best thing to do anyway.)

More broadly though, the reason this came up for me was that I wrote my own KitClientManager singleton, which itself kept a reference to the KitClient instance, because my app has both an Activity and a Service that need to access P2P Services, and if either of these calls KitClient.disconnect(), then the other is also disconnected. Therefore, I use the KitClientManager to keep track of how many listeners are using the KitClient, and only disconnect once there are no listeners remaining. Perhaps this is something that could be changed, or if there is a better way for me to do this I would be happy to hear it.

Thanks for your help!

**Comment by thupa** [comment]
Your approach does not seem to bad to me, what you could do is check if KitClient is connected or not before connecting...

May i ask why would you want to disconnect in the first place?

In that case, have a look at the following method which will tell you when p2p discovery is no longer needed and its safe to disconnect. This method will return STATE_OFF (-1) if there are no p2p listeners registered..

```java
KitClient.getInstance(this).getDiscoveryServices().checkP2pDiscoveryWorkingState()
```

http://p2pkit.io/javadoc/reference/ch/uepaa/p2pkit/discovery/DiscoveryServices.html#checkP2pDiscoveryWorkingState()

**Comment by Dagwaging** [comment]
It seems like good practice to disconnect from the service when it is not needed, to save resources, but maybe this isn't necessary?

Thank you for the tip about checkP2pDiscoveryWorkingState(), it wasn't clear to me from the documentation that this reflects whether there are any listeners registered or not.

**Comment by thupa** [comment]
You can disconnect from the services when you don't need it. But in general, the API's will only work if there is at least one listener registered.

Good Luck!
